version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_1
    restart: always
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: bridge
