version: "3.7"
services:
  mockserver:
    image: jamesdbloom/mockserver:mockserver-5.11.1
    container_name: mockserver
    hostname: mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mocks/init.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      - ./ambiente_local/mocks:/mocks